### ISSUE TITLE
Minor Clean-ups

### ISSUE THREAD

**Issue by lgranger** [noglows/betsy#6]
products controller line 50: `if !params[:categories].nil?` to `if params[:categories]`

**Comment by lgranger** [comment]
ternary operators in orders controller? lines 14/15

`if oi.order.status == params[:sort]
            if @orders.include? oi.order` 

to 

`@orders.include?(oi.order) ? next : @orders.push(oi.order)`

**Comment by lgranger** [comment]
in order.rb lines 4-6

"Instead of doing an .each here you can use the Rails built-in validates_presence_of instance method.
e.g.

`validates_presence_of :email, :mailing_address, :zip, :name_on_card, :last_four, :card_exp, on: :update`"

**Comment by lgranger** [comment]
remove extra whitespaces

**Comment by lacuchilla** [comment]
I do it.

**Comment by lacuchilla** [comment]
I did it!
